### ISSUE TITLE
help_console not working for nlme:::corClasses

### ISSUE THREAD

**Issue by myaseen208** [noamross/noamtools#3]
help_console not working for corClasses function from nlme package.

help_console(topic = corClasses, format = "latex")

Error in help_console(topic = corClasses, format = "latex") : 
  object 'corClasses' not found

See here http://stackoverflow.com/q/21046970/707145

**Comment by wleoncio** [comment]
Unfortunately, `help_console` is not even part of the master branch anymore, should this be closed?

**Comment by noamross** [comment]
Yup, thanks. I believe this feature is in base knitr now.

**Comment by wleoncio** [comment]
> I believe this feature is in base knitr now.

This is good news, I'll look into that!
